apiVersion: v1
kind: Service
metadata:
  name: analyzercore-service
  labels:
    app: analyzercore-service
spec:
  ports:
    - name: http
      port: 8084
  selector:
    app: analyzercore-service
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: analyzercore-service
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: analyzercore-service
        version: v1
    spec:
      containers:
        - name: analyzercore-app
          image: gcr.io/brainiac-265813/coreengine:latest
          env:
            - name: MONGODB_HOST
              value: mongodb
          ports:
            - containerPort: 8084