apiVersion: v1
kind: Service
metadata:
  name: usermanagement-service
  labels:
    app: usermanagement-service
spec:
  ports:
    - name: http
      port: 8000
  selector:
    app: usermanagement-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: usermanagement-service
  labels: 
    app: usermanagement-service
spec:
  replicas: 1
  selector:
    matchLabels: # backend application pod labels should match these
      app: usermanagement-service
  template:
    metadata:
      labels:
        app: usermanagement-service
        version: v1
    spec:
      containers:
        - name: usermanagement-app
          image: usermgmt
          imagePullPolicy: Never
          env:
            - name: MONGODB_HOST
              value: mongodb
          ports:
            - containerPort: 8000
          livenessProbe:
            httpGet:
              path: /
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 5
